-- Use this script to create the 'staging' table in staging area in PostgreSQL

CREATE TABLE IF NOT EXISTS staging (
    transaction_id integer,
    transaction_date date,
    sales_outlet_id integer,
    staff_id integer,
    customer_id integer,
    sales_detail_id integer,
    product_id integer,
    quantity integer,
    price numeric(15, 2),
    staff_first_name character varying(50),
    staff_last_name character varying(50),
    staff_position character varying(50),
    staff_location character varying(5),
    sales_outlet_type character varying(20),
    outlet_address character varying(50),
    outlet_city character varying(40),
    outlet_telephone character varying(15),
    outlet_postal_code integer,
    outlet_manager integer,
    customer_name character varying(50),
    customer_email character varying(50),
    card_number character varying(15),
    gender_desc character varying(10),
    product_name character varying(100),
    description character varying(250),
    product_price numeric(15, 2),
    product_type_id integer,
    product_type character varying(50),
    product_category character varying(50),
    customer_gender_id integer,
    city_id integer,
    month_id integer,
    year integer,
    day_of_week_id integer,
    day_of_week character varying(10),
    month_name character varying(10),
    year_id integer,
    date_id integer
);

ALTER TABLE staging ADD PRIMARY KEY (transaction_id);